/**
 * Schema types for settings.json structure.
 *
 * These types define the output format of `serializeSettings()` and represent
 * the public contract for settings.json files generated by the CLI.
 *
 *
 * @summary Schema types for settings.json structure
 * @module schema
 */

// ============================================================================
// Command
// ============================================================================

/**
 * Represents a command to execute.
 *
 * Commands define executable scripts or binaries with optional timeout constraints.
 *
 * @example
 * ```typescript
 * const cmd: Command = {
 *   command: 'node ./bin/launch-start.js',
 *   timeout: 30000
 * };
 * ```
 */
export interface Command {
  /** The command string to execute (script path or binary) */
  command: string;
  /** Optional timeout in milliseconds */
  timeout?: number;
}

// ============================================================================
// Action
// ============================================================================

/**
 * Represents an action with a single command.
 *
 * Actions are user-facing operations that can be triggered through the UI.
 * Each action has a single command that handles the full action lifecycle.
 *
 * @example
 * ```typescript
 * const action: Action = {
 *   id: 'launch-claude',
 *   name: 'Launch Claude',
 *   description: 'Launch Claude in a new window',
 *   icon: 'rocket',
 *   command: { command: 'node ./bin/action-Launch Claude.js' },
 *   supportsBackgroundMode: true,
 *   allowConcurrent: false
 * };
 * ```
 */
export interface Action {
  /** Unique identifier for the action (generated by CLI via slugify) */
  id: string;
  /** Display name for the action */
  name: string;
  /** Optional description shown to users */
  description?: string;
  /** Optional icon identifier */
  icon?: string;
  /** Command to execute for this action */
  command: Command;
  /** Whether the action can run in background mode */
  supportsBackgroundMode?: boolean;
  /** Whether multiple instances can run concurrently */
  allowConcurrent?: boolean;
}

// ============================================================================
// TypeDefinition
// ============================================================================

/**
 * Represents a typed file configuration with lifecycle hooks.
 *
 * Type definitions specify how to validate, create, update, and delete
 * typed files in the Cards Extension.
 *
 * @example
 * ```typescript
 * const typeDef: TypeDefinition = {
 *   version: '1.0.0',
 *   validator: { command: 'node ./bin/note-validator.js' },
 *   create: { command: 'node ./bin/note-create.js' },
 *   update: { command: 'node ./bin/note-update.js' },
 *   delete: { command: 'node ./bin/note-delete.js' }
 * };
 * ```
 */
export interface TypeDefinition {
  /** Version string for the type definition */
  version: string;
  /** Optional validator command for typed files */
  validator?: Command;
  /** Optional command for creating new typed files */
  create?: Command;
  /** Optional command for updating typed files */
  update?: Command;
  /** Optional command for deleting typed files */
  delete?: Command;
  /** Human-readable schema describing the expected file format. */
  schema?: string;
  /** Description of the type's purpose. */
  description?: string;
}

// ============================================================================
// StreamDefinition
// ============================================================================

/**
 * Represents a stream configuration with transform and size constraints.
 *
 * Stream definitions specify how to transform JSONL streams and set limits
 * on line length and total stream size.
 *
 * @example
 * ```typescript
 * const streamDef: StreamDefinition = {
 *   version: 1,
 *   transform: { path: './bin/transform.js', timeout: 5000 },
 *   maxLineLength: 1024,
 *   maxStreamSize: 1048576
 * };
 * ```
 */
export interface StreamDefinition {
  /** Version number for the stream definition */
  version: number;
  /** Transform configuration with script path and optional timeout */
  transform: { path: string; timeout?: number };
  /** Optional maximum length for a single line in bytes */
  maxLineLength?: number;
  /** Optional maximum total stream size in bytes */
  maxStreamSize?: number;
}

// ============================================================================
// Environment
// ============================================================================

/**
 * Represents a configuration environment.
 *
 * Environments group actions and type definitions together, allowing
 * different configurations for different contexts (e.g., development, production).
 *
 * @example
 * ```typescript
 * const env: Environment = {
 *   version: 1,
 *   description: 'Development environment',
 *   actions: [
 *     {
 *       name: 'Launch Claude',
 *       start: { command: 'node ./bin/launch-start.js' }
 *     }
 *   ],
 *   types: {
 *     note: {
 *       version: '1.0.0',
 *       validator: { command: 'node ./bin/note-validator.js' }
 *     }
 *   }
 * };
 * ```
 */
export interface Environment {
  /** Schema version number */
  version: number;
  /** Optional description of the environment */
  description?: string;
  /** Array of actions available in this environment */
  actions: Action[];
  /** Optional record of type definitions keyed by type name */
  types?: Record<string, TypeDefinition>;
  /** Optional record of stream definitions keyed by stream name */
  streams?: Record<string, StreamDefinition>;
}

// ============================================================================
// Settings
// ============================================================================

/**
 * Root settings.json structure.
 *
 * Settings contain one or more environments, each with their own actions
 * and type definitions. This is the top-level structure written to settings.json.
 *
 * @example
 * ```typescript
 * const settings: Settings = {
 *   environments: {
 *     default: {
 *       version: 1,
 *       actions: [
 *         {
 *           name: 'Launch Claude',
 *           start: { command: 'node ./bin/launch-start.js' }
 *         }
 *       ]
 *     },
 *     production: {
 *       version: 1,
 *       actions: []
 *     }
 *   }
 * };
 * ```
 */
export interface Settings {
  /** Record of environments keyed by environment name */
  environments: Record<string, Environment>;
}
