/**
 * Schema types for settings.json structure.
 *
 * These types define the output format of `serializeSettings()` and represent
 * the public contract for settings.json files generated by the CLI.
 *
 *
 * @summary Schema types for settings.json structure
 * @module schema
 */

// ============================================================================
// Command
// ============================================================================

/**
 * Represents a command to execute.
 *
 * Commands define executable scripts or binaries with optional timeout constraints.
 *
 * @example
 * ```typescript
 * const cmd: Command = {
 *   command: 'node ./bin/launch-start.js',
 *   timeout: 30000
 * };
 * ```
 */
export interface Command {
  /** The command string to execute (script path or binary) */
  command: string;
  /** Optional timeout in milliseconds */
  timeout?: number;
}

// ============================================================================
// Action
// ============================================================================

/**
 * Represents an action with a single command.
 *
 * Actions are user-facing operations that can be triggered through the UI.
 * Each action has a single command that handles the full action lifecycle.
 *
 * @example
 * ```typescript
 * const action: Action = {
 *   id: 'launch-claude',
 *   name: 'Launch Claude',
 *   description: 'Launch Claude in a new window',
 *   icon: 'rocket',
 *   command: { command: 'node ./bin/action-Launch Claude.js' },
 *   supportsBackgroundMode: true,
 *   allowConcurrent: false
 * };
 * ```
 */
export interface Action {
  /** Unique identifier for the action (generated by CLI via slugify) */
  id: string;
  /** Display name for the action */
  name: string;
  /** Optional description shown to users */
  description?: string;
  /** Optional icon identifier */
  icon?: string;
  /** Command to execute for this action */
  command: Command;
  /** Whether the action can run in background mode */
  supportsBackgroundMode?: boolean;
  /** Whether multiple instances can run concurrently */
  allowConcurrent?: boolean;
}

// ============================================================================
// StreamDefinition
// ============================================================================

/**
 * Represents a stream configuration with an iframe renderer and size constraints.
 *
 * Stream definitions specify a static directory (`wwwRoot`) containing an
 * iframe-based renderer and set limits on line length and total stream size.
 *
 * @example
 * ```typescript
 * const streamDef: StreamDefinition = {
 *   version: 1,
 *   wwwRoot: './renderers/claude-session',
 *   entrypoint: 'index.html',
 *   maxLineLength: 1024,
 *   maxStreamSize: 1048576
 * };
 * ```
 */
export interface StreamDefinition {
  /** Version number for the stream definition */
  version: number;
  /** Path to the directory containing the iframe renderer's static assets */
  wwwRoot: string;
  /** Entry point HTML file within the wwwRoot directory. Defaults to "index.html". */
  entrypoint?: string;
  /** Optional maximum length for a single line in bytes */
  maxLineLength?: number;
  /** Optional maximum total stream size in bytes */
  maxStreamSize?: number;
}

// ============================================================================
// Environment
// ============================================================================

/**
 * Represents a configuration environment.
 *
 * Environments group actions and stream definitions together, allowing
 * different configurations for different contexts (e.g., development, production).
 *
 * @example
 * ```typescript
 * const env: Environment = {
 *   version: 1,
 *   description: 'Development environment',
 *   actions: [
 *     {
 *       name: 'Launch Claude',
 *       start: { command: 'node ./bin/launch-start.js' }
 *     }
 *   ]
 * };
 * ```
 */
export interface Environment {
  /** Schema version number */
  version: number;
  /** Optional description of the environment */
  description?: string;
  /** Array of actions available in this environment */
  actions: Action[];
  /** Optional record of stream definitions keyed by stream name */
  streams?: Record<string, StreamDefinition>;
}

// ============================================================================
// Settings
// ============================================================================

/**
 * Root settings.json structure.
 *
 * Settings contain one or more environments, each with their own actions
 * and type definitions. This is the top-level structure written to settings.json.
 *
 * @example
 * ```typescript
 * const settings: Settings = {
 *   environments: {
 *     default: {
 *       version: 1,
 *       actions: [
 *         {
 *           name: 'Launch Claude',
 *           start: { command: 'node ./bin/launch-start.js' }
 *         }
 *       ]
 *     },
 *     production: {
 *       version: 1,
 *       actions: []
 *     }
 *   }
 * };
 * ```
 */
// ============================================================================
// CardsAssistant
// ============================================================================

/**
 * Cards assistant handler configuration in settings.json.
 *
 * Defines the command used to launch the cards assistant, which operates
 * outside the per-card action pipeline (no card context, no worktree,
 * no socket, no ActionDispatcher).
 *
 * @example
 * ```typescript
 * const assistant: CardsAssistant = {
 *   command: { command: '"$VSCODE_NODE" ./bin/cards-assistant.abc12345.mjs' }
 * };
 * ```
 */
export interface CardsAssistant {
  /** Command to execute for the cards assistant handler */
  command: Command;
}

export interface Settings {
  /** Record of environments keyed by environment name */
  environments: Record<string, Environment>;

  /** Optional cards assistant handler configuration */
  cardsAssistant?: CardsAssistant;
}
