name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and resolve the issue.

  - type: checkboxes
    id: search
    attributes:
      label: Existing Issues
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Which version of Compare Branch are you using? (find in Extensions panel)
      placeholder: 'e.g., 0.5.66'
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: Which version of VS Code are you using? (Help → About)
      placeholder: 'e.g., 1.85.0'
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS and version are you using?
      placeholder: 'e.g., macOS 14.1, Windows 11, Ubuntu 22.04'
    validations:
      required: true

  - type: input
    id: git-version
    attributes:
      label: Git Version
      description: Which version of git are you using? (run `git --version`)
      placeholder: 'e.g., 2.42.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Open a git repository
        2. Click on '...'
        3. Select '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: If applicable, add screenshots or error logs
      placeholder: Paste screenshots or logs here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context here
