blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/goodfoot-io/compare-branch-extension/discussions
    about: For questions, ideas, and community discussion
  - name: Security Issue
    url: https://github.com/goodfoot-io/compare-branch-extension/security/advisories/new
    about: Report security vulnerabilities privately
