/**
 * Reproduction + contract tests for cross-layer plugin load-identity collision
 * (card main-616).
 *
 * OpenCode layers plugin origins across configs (global user scope, then
 * `OPENCODE_CONFIG`, then project) and deduplicates ONLY by load identity:
 * the npm package name for bare specs, the exact file URL for local file
 * specs. The user-scope installer registers the Cards interaction plugin in
 * the global layer as the stable pointer spec
 * (`<configDir>/plugins/cache/cards/cards/current.mjs`); the launch stager
 * enumerated absolute per-hook entry URLs instead. Distinct identities ⇒ both
 * layers loaded ⇒ every Cards hook executed twice in dispatched sessions.
 *
 * These cases model that loader semantics over the two documents Cards writes
 * and lock in the single-registration outcome: the staged document must carry
 * the byte-identical pointer spec for globally registered plugins (so the
 * loader's own dedupe collapses the layers) and keep direct entry paths for
 * plugins with no global registration.
 *
 * @summary Cross-layer hook registration identity tests for staged launch configs
 */

import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('node:fs/promises', () => ({
  constants: { X_OK: 0o1 },
  access: vi.fn(),
  cp: vi.fn(),
  mkdir: vi.fn(),
  mkdtemp: vi.fn(),
  readFile: vi.fn(),
  readdir: vi.fn(),
  rename: vi.fn(),
  rm: vi.fn(),
  stat: vi.fn(),
  writeFile: vi.fn()
}));

/**
 * Production code builds paths with node:path; normalize to forward slashes so
 * POSIX-keyed mock lookups match regardless of platform.
 *
 * @param p - Path-like value to normalize.
 * @returns The value stringified with backslashes converted to forward slashes.
 */
function toPosix(p: unknown): string {
  return String(p).replace(/\\/g, '/');
}

/** Synthetic OpenCode config dir standing in for `$XDG_CONFIG_HOME/opencode`. */
const CONFIG_DIR = '/xdg-config/opencode';

/** Cache-root fixture matching the production layout `<configDir>/plugins/cache/cards`. */
const CACHE_ROOT = `${CONFIG_DIR}/plugins/cache/cards`;

/**
 * The spec the user-scope installer registers in the global layer
 * (`opencodePointerPath` in packages/extension/src/agents/install/opencodeLayout.ts):
 * `<configDir>/plugins/cache/cards/<plugin>/current.mjs`.
 */
const GLOBAL_CARDS_POINTER = `${CACHE_ROOT}/cards/current.mjs`;

/** Pointer fixture mirroring `buildCurrentPointerContent`: one default-module re-export per hook module. */
const POINTER_CONTENT = [
  '// Cards-managed stable plugin pointer. Regenerated by the Cards extension installer; edits are overwritten on upgrade.',
  `export { default as cardsPlugin0 } from './1.0.0/plugin/post-tool-use-skill.mjs';`,
  `export { default as cardsPlugin1 } from './1.0.0/plugin/user-prompt-submit.mjs';`,
  ''
].join('\n');

beforeEach(async () => {
  vi.clearAllMocks();
  const fs = await import('node:fs/promises');
  vi.mocked(fs.writeFile).mockResolvedValue(undefined);
  vi.mocked(fs.rm).mockResolvedValue(undefined);
  // The staged document does not exist yet; the pointer file does.
  vi.mocked(fs.readFile).mockImplementation(async (filePath: unknown) => {
    if (toPosix(filePath) === GLOBAL_CARDS_POINTER) {
      return POINTER_CONTENT;
    }
    throw Object.assign(new Error(`mock: ENOENT ${String(filePath)}`), { code: 'ENOENT' });
  });
  vi.mocked(fs.access).mockImplementation(async (filePath: unknown) => {
    if (toPosix(filePath) === GLOBAL_CARDS_POINTER) {
      return undefined;
    }
    throw Object.assign(new Error(`mock: ENOENT ${String(filePath)}`), { code: 'ENOENT' });
  });
});

/**
 * Builds plugin-cache-path fixtures rooted at {@link CACHE_ROOT}, matching the
 * production `<cacheRoot>/<plugin>/<version>` layout.
 *
 * @returns Plugin name → cache dir map covering both launch-set plugins.
 */
function cachePaths(): Record<string, string> {
  return {
    cards: `${CACHE_ROOT}/cards/1.0.0`,
    runtime: `${CACHE_ROOT}/runtime/1.0.0`
  };
}

/**
 * Builds a Dirent-shaped object for readdir-withFileTypes mocks.
 *
 * @param name - Entry name.
 * @returns A minimal file-Dirent-shaped fixture.
 */
function fileDirent(name: string): { name: string; isFile(): boolean; isDirectory(): boolean } {
  return { name, isFile: () => true, isDirectory: () => false };
}

/**
 * Wires the readdir/stat mocks for the two-slot fixture: the cards slot ships
 * two hook modules, the runtime slot one; both ship skill directories.
 */
async function mockPluginTrees(): Promise<void> {
  const fs = await import('node:fs/promises');
  vi.mocked(fs.readdir).mockImplementation(async (targetPath: unknown) => {
    const p = toPosix(targetPath);
    if (p === `${CACHE_ROOT}/cards/1.0.0/plugin`) {
      return [fileDirent('user-prompt-submit.mjs'), fileDirent('post-tool-use-skill.mjs')] as unknown as Awaited<
        ReturnType<typeof fs.readdir>
      >;
    }
    if (p === `${CACHE_ROOT}/runtime/1.0.0/plugin`) {
      return [fileDirent('session-start.mjs')] as unknown as Awaited<ReturnType<typeof fs.readdir>>;
    }
    throw Object.assign(new Error(`mock: unhandled readdir: ${p}`), { code: 'ENOENT' });
  });
  vi.mocked(fs.stat).mockResolvedValue({ isDirectory: () => true } as Awaited<ReturnType<typeof fs.stat>>);
  vi.mocked(fs.mkdir).mockResolvedValue(undefined);
  vi.mocked(fs.mkdtemp).mockImplementation(async (prefix: unknown) => `${toPosix(prefix)}XXXXXX`);
  vi.mocked(fs.rename).mockResolvedValue(undefined);
}

/**
 * Extracts the serialized staged document from the fs writeFile mock.
 *
 * @returns The parsed staged config document.
 */
async function readStagedDocument(): Promise<{ plugin: string[]; [key: string]: unknown }> {
  const fs = await import('node:fs/promises');
  const writeCalls = vi.mocked(fs.writeFile).mock.calls;
  expect(writeCalls.length).toBeGreaterThan(0);
  return JSON.parse(String(writeCalls[0]![1])) as { plugin: string[]; [key: string]: unknown };
}

// ---------------------------------------------------------------------------
// Model of the pinned v1.18.x loader semantics (see card main-616 and
// main-614's notes/opencode-loader-source-map.md): origins concat across
// layers; dedupe iterates the reversed list so the LAST occurrence of an
// identity wins; identity is the exact file URL for local specs.
// ---------------------------------------------------------------------------

/**
 * Computes a plugin spec's load identity the way the loader does for local
 * file specs: the exact file URL string.
 *
 * @param spec - A `plugin` array entry (absolute local file spec in these fixtures).
 * @returns The identity string.
 */
function loadIdentity(spec: string): string {
  return pathToFileURL(spec).href;
}

/**
 * Merges plugin origins the way `mergePluginOrigins` + `deduplicatePluginOrigins`
 * do: concatenate layers in order, collapse same-identity entries with last-wins.
 *
 * @param layers - One array of specs per config layer, global first.
 * @returns Surviving origin specs in first-appearance order.
 */
function mergeAndDedupe(...layers: ReadonlyArray<readonly string[]>): string[] {
  const byIdentity = new Map<string, string>();
  for (const layer of layers) {
    for (const spec of layer) {
      byIdentity.set(loadIdentity(spec), spec);
    }
  }
  return [...byIdentity.values()];
}

/**
 * Expands one surviving origin into the concrete hook-module URLs it loads:
 * pointer files contribute every module they re-export; direct entry specs
 * contribute themselves.
 *
 * @param origin - A surviving origin spec.
 * @returns Absolute hook-module paths loaded by this origin.
 */
async function expandOrigin(origin: string): Promise<string[]> {
  const normalized = toPosix(origin);
  if (!normalized.endsWith('/current.mjs')) {
    return [normalized];
  }
  const fs = await import('node:fs/promises');
  const content = await fs.readFile(normalized, 'utf-8');
  return [...content.matchAll(/export \{ default as cardsPlugin\d+ \} from '\.\/([^']+)';/g)].map((match) =>
    toPosix(join(normalized, '..', match[1]!))
  );
}

/**
 * Counts effective hook-module registrations across all surviving origins.
 *
 * @param origins - Surviving origin specs after layer merge + dedupe.
 * @returns Hook-module path → registration count.
 */
async function countRegistrations(origins: readonly string[]): Promise<Map<string, number>> {
  const counts = new Map<string, number>();
  for (const origin of origins) {
    for (const module_ of await expandOrigin(origin)) {
      counts.set(module_, (counts.get(module_) ?? 0) + 1);
    }
  }
  return counts;
}

describe('readGlobalPluginEntries', () => {
  /**
   * Serves a global config document body for the synthetic config dir.
   *
   * @param body - File content served for `<configDir>/opencode.json`.
   */
  async function serveGlobalDoc(body: string): Promise<void> {
    const fs = await import('node:fs/promises');
    vi.mocked(fs.readFile).mockImplementation(async (filePath: unknown) => {
      if (toPosix(filePath) === `${CONFIG_DIR}/opencode.json`) {
        return body;
      }
      throw Object.assign(new Error(`mock: ENOENT ${String(filePath)}`), { code: 'ENOENT' });
    });
  }

  it('returns the registered plugin specs from the global document', async () => {
    await serveGlobalDoc(
      JSON.stringify({
        $schema: 'https://opencode.ai/config.json',
        plugin: [GLOBAL_CARDS_POINTER, 'opencode-git-span']
      })
    );
    const { readGlobalPluginEntries } = await import('../src/lib/opencode-session.js');

    const result = await readGlobalPluginEntries(CONFIG_DIR);

    expect(result.entries).toEqual([GLOBAL_CARDS_POINTER, 'opencode-git-span']);
    expect(result.failure).toBeUndefined();
  });

  it('treats an absent global document as no registrations, not a failure', async () => {
    const { readGlobalPluginEntries } = await import('../src/lib/opencode-session.js');

    const result = await readGlobalPluginEntries(CONFIG_DIR);

    expect(result).toEqual({ entries: [] });
  });

  it('reports unparseable JSON as a failure with no entries', async () => {
    await serveGlobalDoc('{ not json');
    const { readGlobalPluginEntries } = await import('../src/lib/opencode-session.js');

    const result = await readGlobalPluginEntries(CONFIG_DIR);

    expect(result.entries).toEqual([]);
    expect(result.failure).toBe('unparseable');
  });

  it('reports a non-array "plugin" key as untrustworthy rather than staging against it', async () => {
    await serveGlobalDoc(JSON.stringify({ plugin: '/not/an/array' }));
    const { readGlobalPluginEntries } = await import('../src/lib/opencode-session.js');

    const result = await readGlobalPluginEntries(CONFIG_DIR);

    expect(result.entries).toEqual([]);
    expect(result.failure).toBe('unparseable');
  });

  it('keeps only string entries when the registered array carries foreign shapes', async () => {
    await serveGlobalDoc(JSON.stringify({ plugin: [GLOBAL_CARDS_POINTER, ['/tuple', {}], 42] }));
    const { readGlobalPluginEntries } = await import('../src/lib/opencode-session.js');

    const result = await readGlobalPluginEntries(CONFIG_DIR);

    expect(result.entries).toEqual([GLOBAL_CARDS_POINTER]);
    expect(result.failure).toBeUndefined();
  });
});

describe('staged launch config vs global registration — single hook registration', () => {
  it('collapses the globally registered cards plugin to one registration per hook module', async () => {
    await mockPluginTrees();
    const { writeCardsLaunchConfig } = await import('../src/lib/opencode-session.js');

    // The global layer carries the installer's pointer registration, byte
    // identical to what a plain terminal session loads.
    await writeCardsLaunchConfig('/staging', 'launch', ['cards', 'runtime'], cachePaths(), {
      globalPluginEntries: [GLOBAL_CARDS_POINTER]
    });

    const doc = await readStagedDocument();
    const surviving = mergeAndDedupe([GLOBAL_CARDS_POINTER], doc.plugin);
    const counts = await countRegistrations(surviving);

    expect([...counts.entries()].sort()).toEqual(
      [
        `${CACHE_ROOT}/cards/1.0.0/plugin/post-tool-use-skill.mjs`,
        `${CACHE_ROOT}/cards/1.0.0/plugin/user-prompt-submit.mjs`,
        `${CACHE_ROOT}/runtime/1.0.0/plugin/session-start.mjs`
      ].map((module_) => [module_, 1])
    );
  });

  it('keeps direct entry paths when the plugin carries no global registration', async () => {
    await mockPluginTrees();
    const fs = await import('node:fs/promises');
    const { writeCardsLaunchConfig } = await import('../src/lib/opencode-session.js');

    await writeCardsLaunchConfig('/staging', 'launch', ['cards', 'runtime'], cachePaths(), {
      globalPluginEntries: []
    });

    const doc = await readStagedDocument();
    // Nothing to collide with: the enumerated entry paths are the correct,
    // self-contained staging for a plugin the global layer never registered.
    expect(doc.plugin).toEqual([
      `${CACHE_ROOT}/cards/1.0.0/plugin/post-tool-use-skill.mjs`,
      `${CACHE_ROOT}/cards/1.0.0/plugin/user-prompt-submit.mjs`,
      `${CACHE_ROOT}/runtime/1.0.0/plugin/session-start.mjs`
    ]);

    const counts = await countRegistrations(mergeAndDedupe([], doc.plugin));
    expect([...counts.values()].every((count) => count === 1)).toBe(true);

    // The pointer was never consulted for existence in this path.
    expect(vi.mocked(fs.access)).not.toHaveBeenCalled();
  });

  it('falls back to entry paths when the globally registered pointer file is missing on disk', async () => {
    await mockPluginTrees();
    const fs = await import('node:fs/promises');
    vi.mocked(fs.stat).mockRejectedValue(Object.assign(new Error('ENOENT'), { code: 'ENOENT' }));
    const { writeCardsLaunchConfig } = await import('../src/lib/opencode-session.js');

    // Registration claims the pointer, but the cache subtree lost it (wiped or
    // partially repaired). Staging the dead spec would break the session; the
    // entry paths are verified to exist — populateOpencodePluginCache just
    // published them — so they remain the safe staging.
    await writeCardsLaunchConfig('/staging', 'launch', ['cards', 'runtime'], cachePaths(), {
      globalPluginEntries: [GLOBAL_CARDS_POINTER]
    });

    const doc = await readStagedDocument();
    expect(doc.plugin).toEqual([
      `${CACHE_ROOT}/cards/1.0.0/plugin/post-tool-use-skill.mjs`,
      `${CACHE_ROOT}/cards/1.0.0/plugin/user-prompt-submit.mjs`,
      `${CACHE_ROOT}/runtime/1.0.0/plugin/session-start.mjs`
    ]);
  });

  it('substitutes the pointer spec only for plugins whose exact pointer is registered', async () => {
    await mockPluginTrees();
    const { writeCardsLaunchConfig } = await import('../src/lib/opencode-session.js');

    // A stale-shaped managed entry (version slot path, not the pointer) in the
    // global layer is NOT byte-identical to the pointer spec — it cannot
    // collide, so the staged document must keep the entry paths for that
    // plugin rather than assume a collision that will never happen.
    await writeCardsLaunchConfig('/staging', 'launch', ['cards', 'runtime'], cachePaths(), {
      globalPluginEntries: [`${CACHE_ROOT}/cards/1.0.0/plugin/user-prompt-submit.mjs`]
    });

    const doc = await readStagedDocument();
    expect(doc.plugin).toEqual([
      `${CACHE_ROOT}/cards/1.0.0/plugin/post-tool-use-skill.mjs`,
      `${CACHE_ROOT}/cards/1.0.0/plugin/user-prompt-submit.mjs`,
      `${CACHE_ROOT}/runtime/1.0.0/plugin/session-start.mjs`
    ]);
  });
});
