/**
 * Canonical wire-level type definitions and constraint constants shared across
 * the Cards V2 ecosystem. Defines the JSON-serializable shapes for cards,
 * REST API requests and responses, WebSocket domain events,
 * webview communication, settings, and validation boundaries. Contains no
 * runtime behavior.
 *
 * @summary Shared protocol types and constants for the Cards V2 wire format
 * @module
 */

// --- Status Types ---
// --- Card Types ---
// --- API Discovery Types ---
// --- Response Envelope Types ---
// --- WebSocket Event Types ---
// --- Webview Messaging Types ---
// --- Custom Types ---
// --- API Request/Response Types ---
// --- Remote Programmatic API Types ---
export type {
  Action,
  ActionMessage,
  ActionResult,
  ActionState,
  ActionSummaryResponse,
  ActivityStateResponse,
  AddBranchRequest,
  AddCommitRequest,
  ApiError,
  ApiRequestMessage,
  ApiResponseMessage,
  ApiSuccess,
  AsyncFileExistsCallback,
  AsyncListFilesCallback,
  AsyncReadFileCallback,
  AsyncWriteFileCallback,
  AttachmentAddedEvent,
  AttachmentInfoFile,
  AttachmentRemovedEvent,
  AttachmentResponse,
  BranchesResponse,
  BranchInfo,
  CancelAcknowledgment,
  CancelCommand,
  Card,
  CardCommit,
  CardCommitDiffUnavailable,
  CardCommitEvent,
  CardCommitFile,
  CardCreatedEvent,
  CardCreateGates,
  CardDeletedEvent,
  CardDetailMessage,
  CardGates,
  CardIncomingRelationsChangedEvent,
  CardJournalClientMessage,
  CardJournalEntry,
  CardJournalEventMessage,
  CardJournalServerMessage,
  CardMetadata,
  CardPostCommitRequest,
  CardPostCommitResponse,
  CardRelation,
  CardRelationType,
  CardReplayMessage,
  CardResponse,
  CardSnapshot,
  CardSnapshotMessage,
  CardStatus,
  CardSubscribeFailedMessage,
  CardSubscribeMessage,
  CardsApiInfo,
  CardsAssistant,
  CardsMetadataEvent,
  CardUnsubscribeMessage,
  Command,
  Comment,
  CommentCreatedEvent,
  CommentResponse,
  CommentTimelineItem,
  CommitAttributionResponse,
  CommitAuthor,
  CommitDetails,
  CommitStats,
  CommitTimelineItem,
  CompareBranchRangeRequest,
  CompareChangedEvent,
  CompareClearedEvent,
  CompareDynamicRequest,
  CompareFixedAttributionRequest,
  CompareMode,
  CompareRequest,
  CompareState,
  ConnectionsResponse,
  CreateAttachmentRequest,
  CreateCardRequest,
  CreateCommentRequest,
  DomainEvent,
  Environment,
  EnvironmentInfo,
  EnvironmentsResponse,
  EventMessage,
  ExecuteActionRequest,
  ExecutionMode,
  ExtensionToWebviewMessage,
  FieldError,
  FileChange,
  FileExistsCallback,
  GateApprovalResponse,
  GateName,
  HasUpdatesResponse,
  HealthResponse,
  HookConfig,
  HookEvent,
  HookScript,
  HtmlContentCheckResult,
  HtmlInfoFile,
  HtmlInfoValidationResult,
  HttpClient,
  LaunchClaudeAction,
  ListCardsRequest,
  ListFilesCallback,
  ListTagsRequest,
  MergeStatusSnapshot,
  MergeStatusValue,
  NavigateMessage,
  NotificationCreateRequest,
  NotificationSeverity,
  ProcessState,
  ReadFileCallback,
  ServerChangedMessage,
  SessionBaseline,
  SessionType,
  Settings,
  StaleMergeStatusValue,
  StateUpdateMessage,
  StreamDefinition,
  StreamEndedEvent,
  StreamErrorEvent,
  StreamLineEvent,
  StreamMeta,
  StreamMetaFile,
  StreamResumedEvent,
  StreamStartedEvent,
  SwitchToInteractiveCommand,
  TagsResponse,
  ThemeUpdateMessage,
  TimelineCommentAddedEvent,
  TimelineCommentRemovedEvent,
  TimelineCommentUpdatedEvent,
  TimelineCommitAddedEvent,
  TimelineCommitRemovedEvent,
  TimelineItem,
  TimelineRequest,
  TimelineResponse,
  UpdateCardRequest,
  UpdateCommentRequest,
  ValidationErrorCode,
  ValidationErrorMessage,
  WebviewAction,
  WebviewDidConnectMessage,
  WebviewState,
  WebviewTimelineEntry,
  WebviewToExtensionMessage,
  WorkspaceBranch,
  WorkspaceCommitEvent,
  WorkspacePostCommitRequest,
  WorkspacePostCommitResponse,
  WrapperCommand,
  WrapperErrorResponse,
  WrapperResponse
} from './types/index.js';
// --- Input Constraints ---
// --- Card Gates ---
export {
  ATTACHMENT_ID_PATTERN,
  BRANCHES_DIR,
  CARD_RELATION_TYPES,
  COMMITS_DIR,
  checkHtmlContent,
  DEFAULT_CARD_GATES,
  EMPTY_TREE_SHA,
  filterStructuralParseErrors,
  findExternalResources,
  INFORMATIONAL_PARSE5_CODES,
  MAX_CARD_ID_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MAX_ID_LENGTH,
  MAX_SUMMARY_LENGTH,
  MAX_TAG_LENGTH,
  MAX_TITLE_LENGTH,
  parseAspectRatio,
  TAG_PATTERN,
  validateHtmlInfo
} from './types/index.js';
