/**
 * Canonical wire-level type definitions and constraint constants shared across
 * the Cards V2 ecosystem. Defines the JSON-serializable shapes for cards,
 * REST API requests and responses, WebSocket domain events, IPC messages,
 * webview communication, settings, and validation boundaries. Contains no
 * runtime behavior.
 *
 * @summary Shared protocol types and constants for the Cards V2 wire format
 * @module
 */

// --- Status Types ---
// --- Card Types ---
// --- API Discovery Types ---
// --- Response Envelope Types ---
// --- WebSocket Event Types ---
// --- IPC Message Types ---
// --- Webview Messaging Types ---
// --- Custom Types ---
// --- API Request/Response Types ---
export type {
  Action,
  ActionMessage,
  ActionResult,
  ActionState,
  ActionSummaryResponse,
  ActivityStateResponse,
  AddBranchRequest,
  AddCommitRequest,
  ApiError,
  ApiRequestMessage,
  ApiResponseMessage,
  ApiSuccess,
  AsyncFileExistsCallback,
  AsyncReadFileCallback,
  AsyncWriteFileCallback,
  AttachmentAddedEvent,
  AttachmentInfoFile,
  AttachmentRemovedEvent,
  AttachmentResponse,
  BranchesResponse,
  BranchInfo,
  CancelAcknowledgment,
  CancelCommand,
  Card,
  CardContentChangedEvent,
  CardCreateGates,
  CardDeletedEvent,
  CardDetailMessage,
  CardGates,
  CardIncomingBlocksChangedEvent,
  CardMetadata,
  CardMetadataChangedEvent,
  CardRelation,
  CardRelationType,
  CardResponse,
  CardSnapshot,
  CardStatus,
  CardsApiInfo,
  Command,
  Comment,
  CommentCreatedEvent,
  CommentResponse,
  CommentTimelineItem,
  CommitAttributionResponse,
  CommitAuthor,
  CommitDetails,
  CommitStats,
  CommitTimelineItem,
  CompareBranchRangeRequest,
  CompareChangedEvent,
  CompareClearedEvent,
  CompareDynamicRequest,
  CompareFixedAttributionRequest,
  CompareMode,
  CompareRequest,
  CompareState,
  ConnectionFailedMessage,
  ConnectionsResponse,
  CreateAttachmentRequest,
  CreateCardRequest,
  CreateCommentRequest,
  DomainEvent,
  Environment,
  EnvironmentInfo,
  EnvironmentsResponse,
  EventMessage,
  ExecutionMode,
  ExtensionToWebviewMessage,
  FieldError,
  FileChange,
  FileExistsCallback,
  FsCommit,
  FsCommitEvent,
  FsCommitFile,
  GateApprovalResponse,
  GateName,
  HasUpdatesResponse,
  HealthResponse,
  HookConfig,
  HookEvent,
  HookScript,
  HttpClient,
  IpcMessage,
  IpcMessageBase,
  IpcMessageCallback,
  LaunchClaudeAction,
  ListCardsRequest,
  ListTagsRequest,
  NavigateMessage,
  NotificationCreateRequest,
  NotificationSeverity,
  PlanResponse,
  ProcessState,
  ReadFileCallback,
  ReindexRequest,
  ReindexResponse,
  SerializedCard,
  ServerChangedMessage,
  SessionBaseline,
  SessionStartedMessage,
  SessionType,
  Settings,
  StateUpdateMessage,
  StreamDefinition,
  StreamEndedEvent,
  StreamErrorEvent,
  StreamLineEvent,
  StreamMeta,
  StreamMetaFile,
  StreamResumedEvent,
  StreamStartedEvent,
  StreamStatus,
  SwitchToInteractiveCommand,
  TagsResponse,
  ThemeUpdateMessage,
  TimelineCommentAddedEvent,
  TimelineCommentRemovedEvent,
  TimelineCommentUpdatedEvent,
  TimelineCommitAddedEvent,
  TimelineCommitRemovedEvent,
  TimelineItem,
  TimelineRequest,
  TimelineResponse,
  TimelineTypedFileAddedEvent,
  TimelineTypedFileRemovedEvent,
  TimelineTypedFileUpdatedEvent,
  TransformContext,
  TypeConfig,
  TypeDefinition,
  TypedFileHookInput,
  TypedFileListResponse,
  TypedFileMetadata,
  TypedFileResponse,
  TypedFileTimelineItem,
  TypesConfig,
  UpdateCardRequest,
  UpdateCommentRequest,
  UpdatePlanRequest,
  ValidationErrorCode,
  ValidationErrorMessage,
  ValidationFailure,
  ValidationResult,
  ValidationSuccess,
  WebviewAction,
  WebviewDidConnectMessage,
  WebviewState,
  WebviewTimelineEntry,
  WebviewToExtensionMessage,
  WorkspaceBranch,
  WorkspaceCommitEvent,
  WrapperCommand,
  WrapperErrorResponse,
  WrapperResponse
} from './types/index.js';
// --- Input Constraints ---
// --- Card Gates ---
export {
  ATTACHMENT_ID_PATTERN,
  CARD_GITIGNORE,
  CARD_RELATION_TYPES,
  DEFAULT_CARD_GATES,
  EMPTY_TREE_SHA,
  MAX_CARD_ID_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MAX_ID_LENGTH,
  MAX_SUMMARY_LENGTH,
  MAX_TAG_LENGTH,
  MAX_TITLE_LENGTH,
  TAG_PATTERN,
  WORKSPACE_BRANCHES_FILE,
  WORKSPACE_COMMITS_FILE
} from './types/index.js';
